### ISSUE TITLE
An options to ignore undefined pass parameters

### ISSUE THREAD

**Issue by purell** [kzmd3/cola#2]
Hi,

I could be great having an option (true/false) to ignore when unknown flag are pass ? If I only defined -b -g and user pass -b -r, then when the ignore option is set to true it is not throwing any exception, cola only ignore them.

Ex : 
```
parser.ignoreUndefinedParam(true);
```

By default thiso option could be set to false.

**Comment by kzmd3** [comment]
Hi,

Sorry for the late reply.

I added a member function 'bool cola::parser::exists_undefined_options() const'.
The function returns true when there are undefined long or short options in parsed argv(see test.cpp).

Thanks for your advice! :-)

**Comment by purell** [comment]
Hi,

No problem for delay :) I don't have enough time to make some test but : Is the new option you added **prevent** cola from throwing an exception regarding unknown flags ? Or it simply indicate when unknown flags are detected and throw an exception anyway ?

Best regards,

**Comment by kzmd3** [comment]
hi,

the added function will not throw an exception, it is only for detect whether the undefined option is passed or not.


best,
